### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when searching or viewing

### ISSUE THREAD

**Issue by rufuspollock** [okfn/ckanjs-deprecated#22]
E.g. on this dataset rkb-explorer-ibm (or a search that would include this dataset) have error:

<pre>
Uncaught RangeError: Maximum call stack size exceeded when searching or viewing
 Model.Resource.Model.Base.extend.toJSON
 . .... lots of recursion ...
</pre>

I note this dataset includes a lot of package relationships and suspect this is to do with how we are trying to deal with children attributes in model ...

**Comment by aron** [comment]
Hmm, the issue is in the serialisation of the models into objects, as the Dataset points to a Resource which points back to the Dataset we get infinite recursion. Ideally we only want to resolve a Model to an object only once in a single call then use a reference after that, perhaps creating and checking a cache of resolved objects before calling `toJSON()` on the model is the way to go, any thoughts?

**Comment by rufuspollock** [comment]
If this is so why aren't we getting this issue on _all_ datasets with resources. E.g. this one displays fine: http://okfn.github.com/ckanjs/app/#dataset/view/d313331b-11c9-487c-b69c-5a6c0f37b67f

I suspect this is something to do with Relationships not Resources.

**Comment by aron** [comment]
Yeah, I've just looked at the code and I have fixed the issue in the Resource model. I'll have to investigate this further.
